In [2]:
import numpy as np
from sklearn.datasets import make_classification

In [3]:
a, b = make_classification(n_samples = 10000, weights = (0.9, 0.1))

In [25]:
a[:5]

array([[-0.95763173,  0.2954063 ,  0.9958381 , -0.0767912 , -0.98657742,
         0.14780149,  0.99239241,  0.33822725,  0.47414488,  0.48979844,
         1.35207445,  0.32085521, -1.67460454,  0.99564083,  0.32215301,
         0.79706882, -0.843123  , -1.41009579,  0.75518612, -1.2273035 ],
       [ 0.50021438, -0.16326352, -0.09804697,  1.08737501,  0.11803062,
         0.11386563,  2.01354346,  1.82154394, -0.42965362, -0.74284651,
        -0.62486881, -2.05594263, -0.02997814,  1.68738144, -0.35172473,
         1.0663552 , -0.29756513, -0.6342671 , -1.4870695 ,  1.92539235],
       [-1.93258668,  0.03241032,  1.08446185,  1.47834395,  0.7051982 ,
         0.83530513, -1.69938901,  0.80823771,  0.34456869,  1.50975491,
         0.14241682,  0.18657754, -1.91103169, -0.00770478, -0.12038554,
         1.38148995, -0.95014926,  0.29981526, -0.53860459, -1.4865979 ],
       [-0.98422309,  0.10614188,  0.85948056,  0.87001011,  1.41616237,
         1.11410423, -0.89112108, -0.56709284,  

In [4]:
b[:10]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
b.shape

(10000,)

In [6]:
id = np.where(b == 0)

In [7]:
id

(array([   0,    2,    3, ..., 9997, 9998, 9999]),)

In [8]:
type(id)

tuple

In [10]:
idx = id[0]

In [13]:
idx[:30]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 31, 32])

In [14]:
type(idx)

numpy.ndarray

In [13]:
idx.shape

(8959,)

In [14]:
idx.sum()

44820886

In [15]:
idx

array([   0,    2,    3, ..., 9997, 9998, 9999])

In [23]:
x0 = a[idx,:]

In [24]:
x0[:5]

array([[-0.95763173,  0.2954063 ,  0.9958381 , -0.0767912 , -0.98657742,
         0.14780149,  0.99239241,  0.33822725,  0.47414488,  0.48979844,
         1.35207445,  0.32085521, -1.67460454,  0.99564083,  0.32215301,
         0.79706882, -0.843123  , -1.41009579,  0.75518612, -1.2273035 ],
       [-1.93258668,  0.03241032,  1.08446185,  1.47834395,  0.7051982 ,
         0.83530513, -1.69938901,  0.80823771,  0.34456869,  1.50975491,
         0.14241682,  0.18657754, -1.91103169, -0.00770478, -0.12038554,
         1.38148995, -0.95014926,  0.29981526, -0.53860459, -1.4865979 ],
       [-0.98422309,  0.10614188,  0.85948056,  0.87001011,  1.41616237,
         1.11410423, -0.89112108, -0.56709284,  0.85117946, -0.88023605,
         2.60459481, -0.44302258, -1.22043859,  0.0712739 ,  2.11472711,
        -0.63323665,  0.06614047,  1.46624837, -0.14376604,  1.07886055],
       [ 0.53551812,  1.55338922,  0.55945426, -1.59747109, -0.70192318,
        -0.19213162,  1.18689372, -2.7922475 ,  

In [18]:
y0 = b[idx]
y0[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
a.shape

(10000, 20)

In [20]:
xx00 = a[idx]
xx00[:5]

array([[-0.95763173,  0.2954063 ,  0.9958381 , -0.0767912 , -0.98657742,
         0.14780149,  0.99239241,  0.33822725,  0.47414488,  0.48979844,
         1.35207445,  0.32085521, -1.67460454,  0.99564083,  0.32215301,
         0.79706882, -0.843123  , -1.41009579,  0.75518612, -1.2273035 ],
       [-1.93258668,  0.03241032,  1.08446185,  1.47834395,  0.7051982 ,
         0.83530513, -1.69938901,  0.80823771,  0.34456869,  1.50975491,
         0.14241682,  0.18657754, -1.91103169, -0.00770478, -0.12038554,
         1.38148995, -0.95014926,  0.29981526, -0.53860459, -1.4865979 ],
       [-0.98422309,  0.10614188,  0.85948056,  0.87001011,  1.41616237,
         1.11410423, -0.89112108, -0.56709284,  0.85117946, -0.88023605,
         2.60459481, -0.44302258, -1.22043859,  0.0712739 ,  2.11472711,
        -0.63323665,  0.06614047,  1.46624837, -0.14376604,  1.07886055],
       [ 0.53551812,  1.55338922,  0.55945426, -1.59747109, -0.70192318,
        -0.19213162,  1.18689372, -2.7922475 ,  

In [21]:
xx00.shape

(8955, 20)

In [22]:
x0.shape

(8955, 20)

In [28]:
idx = np.where(b == 1)[0]
x1 = a[idx, :]
x1[:3]

array([[ 0.50021438, -0.16326352, -0.09804697,  1.08737501,  0.11803062,
         0.11386563,  2.01354346,  1.82154394, -0.42965362, -0.74284651,
        -0.62486881, -2.05594263, -0.02997814,  1.68738144, -0.35172473,
         1.0663552 , -0.29756513, -0.6342671 , -1.4870695 ,  1.92539235],
       [-0.75416814, -1.65870489,  0.431825  , -0.73729312, -0.21078099,
         0.50197414, -0.12267734, -0.42030987,  1.0417285 , -0.27746366,
         0.73318293,  0.72176735, -0.30074073,  0.40323066,  0.17958104,
        -2.15383383,  0.2761618 ,  0.33038635, -0.54257135,  1.33588432],
       [ 0.69812641, -0.24035425, -1.75847338,  0.45086907, -0.53073868,
         0.58650149,  0.27955504,  1.03292026, -2.27273279,  0.11306594,
         1.75006081,  0.89080165,  2.22668877, -0.61188866,  0.11636638,
         2.88365391,  1.03933085,  1.69574242, -2.98300466,  0.25423585]])

In [29]:
y1 = b[idx]
y1[:3]

array([1, 1, 1])

we randomize the ordering

In [30]:
idx = np.argsort(np.random.random(y0.shape))
idx[:15]

array([5432, 7411, 2228, 8933, 7477, 6939, 3231, 8374, 4888, 7321, 7992,
       3139, 3714, 8010, 3660])

In [31]:
y0 = y0[idx]
x0 = x0[idx]

In [32]:
idx = np.argsort(np.random.random(y1.shape))
y1 = y1[idx]
x1 = x1[idx]

Now we extract the first 90% of the samples for training subset

In [33]:
ntrn0 = int(0.9 * x0.shape[0])
ntrn1 = int(0.9 * x1.shape[0])

In [34]:
ntrn0

8059

In [35]:
ntrn1

940

In [38]:
xtrn = np.zeros((ntrn0 + ntrn1, 20))
xtrn[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [39]:
xtrn.shape

(8999, 20)

In [41]:
xtrn[:ntrn0] = x0[:ntrn0]
xtrn[:3]

array([[ 1.48888723,  1.27833244,  0.69818143, -0.21101694, -0.51658659,
        -0.80126214, -0.41896179, -1.24225515,  0.05833789, -0.51392662,
         1.38809842, -0.66567239, -1.31351751, -0.39708347, -0.36416118,
         1.37815834, -1.78293193,  0.16473661,  0.22902626, -0.79515105],
       [ 1.16565498, -1.33584137,  1.20417061,  1.1781049 , -1.07775975,
        -0.34591082, -0.76132787, -1.23147883,  0.62165836, -0.69444966,
         0.34059325,  0.22381181, -2.00035169,  0.00692985, -0.95081519,
         0.81937047,  0.73606602, -1.07441955,  0.81574586, -1.80795171],
       [ 0.45762289, -1.26039465,  1.54726731,  1.05794085, -1.3578362 ,
         1.10021339, -0.79041268, -1.01011252,  0.78448737, -0.26905697,
        -0.05294222,  0.49280389, -2.57757305, -0.4587526 ,  0.36548405,
         1.09556467,  0.16930105,  2.13837837,  0.52756098, -0.13240353]])

In [44]:
ytrn = np.zeros(ntrn0 + ntrn1)
ytrn[:ntrn0] = y0[:ntrn0]
ytrn[:8]

array([0., 0., 0., 0., 0., 0., 0., 0.])

The remaining 5% for validation
Since the order is ramdomized, we can just read sequencially

In [45]:
n0 = int(x0.shape[0] - ntrn0)

In [46]:
n1 = int(x1.shape[0] - ntrn1)

In [48]:
xval = np.zeros((int(n0 / 2 + n1 / 2), 20))
yval = np.zeros(int(n0 / 2 + n1 / 2))

In [50]:
xval[:(n0 // 2)] = x0[ntrn0:(ntrn0 + n0 // 2)]

In [51]:
xval[(n0 // 2):] = x1[ntrn1:(ntrn1 + n1 // 2)]

In [52]:
yval[:(n0 // 2)] = y0[ntrn0:(ntrn0 + n0 // 2)]

In [53]:
yval[(n0 // 2):] = y1[ntrn1:(ntrn1 + n1 // 2)]

The rest 5% is for testing

In [55]:
xtst = np.concatenate((x0[(ntrn0 + n0 // 2):], x1[(ntrn1 + n1 // 2):]))

In [57]:
ytst = np.concatenate((y0[ntrn0 + n0 // 2:], y1[ntrn1 + n1 // 2:]))